/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-06-02 02:02:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/member/../header.jsp", Long.valueOf(1685411068811L));
    _jspx_dependants.put("/WEB-INF/views/member/../footer.jsp", Long.valueOf(1684397965585L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1685607732719L));
    _jspx_dependants.put("jar:file:/C:/Users/B16/Documents/iPet/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ipetProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  \r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("    <html>\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("      <meta charset=\"UTF-8\">\r\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"../resources/assets/css/main.css\" />\r\n");
      out.write("      <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"../resources/images/favicon.jpg\">\r\n");
      out.write("      <title>I-Pet</title>\r\n");
      out.write("      <script src=\"https://code.jquery.com/jquery-3.6.3.js\"></script>\r\n");
      out.write("    </head>\r\n");
      out.write("    <script>\r\n");
      out.write("      $(document).ready(function () {\r\n");
      out.write("        // 로그인 비밀번호찾기 아이디찾기 버튼 클릭시 해당 주소로 이동하는 기능\r\n");
      out.write("        $(\"button\").click(function (e) {\r\n");
      out.write("          e.preventDefault()\r\n");
      out.write("          let id = $(this).attr(\"id\")\r\n");
      out.write("          $(\"form\").attr(\"action\", \"/member/\" + id)\r\n");
      out.write("          if (id == \"findId\") {\r\n");
      out.write("            $.ajax({\r\n");
      out.write("              url: '/member/IdModal', // findId.jsp를 처리하는 URL\r\n");
      out.write("              type: 'GET',\r\n");
      out.write("              success: function (response) {\r\n");
      out.write("                $('#findModal .modal-content').html(response); // 받아온 HTML 코드를 모달의 내용으로 설정\r\n");
      out.write("\r\n");
      out.write("                $(\"#findModal\").css('display', 'block')\r\n");
      out.write("\r\n");
      out.write("              },\r\n");
      out.write("              error: function (error) {\r\n");
      out.write("                console.log(error);\r\n");
      out.write("              }\r\n");
      out.write("            });\r\n");
      out.write("          }\r\n");
      out.write("          else if (id == \"findPassword\") {\r\n");
      out.write("            $.ajax({\r\n");
      out.write("              url: '/member/pwdModal', // findId.jsp를 처리하는 URL\r\n");
      out.write("              type: 'GET',\r\n");
      out.write("              success: function (response) {\r\n");
      out.write("                $('#findModal .modal-content').html(response); // 받아온 HTML 코드를 모달의 내용으로 설정\r\n");
      out.write("\r\n");
      out.write("                $(\"#findModal\").css('display', 'block')\r\n");
      out.write("\r\n");
      out.write("              },\r\n");
      out.write("              error: function (error) {\r\n");
      out.write("                console.log(error);\r\n");
      out.write("              }\r\n");
      out.write("            });\r\n");
      out.write("          }\r\n");
      out.write("          else {\r\n");
      out.write("            if ($(\"input[name=id]\").val().length == 0) alert(\"아이디를 입력해주세요.\")\r\n");
      out.write("            else if ($(\"input[name=password]\").val().length == 0) alert('비밀번호를 입력해 주세요.')\r\n");
      out.write("            // 입력된 id가 없거나 password가 틀리면 error로 이동\r\n");
      out.write("            else {\r\n");
      out.write("              let vo = $(\"form\").serialize()\r\n");
      out.write("              $.ajax({\r\n");
      out.write("                url: \"/member/login\",\r\n");
      out.write("                type: \"post\",\r\n");
      out.write("                dataType: \"json\",\r\n");
      out.write("                data: vo,\r\n");
      out.write("                success: function (result) {\r\n");
      out.write("                  console.log(result)\r\n");
      out.write("                  if (result['message'] == \"1\") {\r\n");
      out.write("                    window.location.href = '/ipet/index';\r\n");
      out.write("                  }\r\n");
      out.write("                  else alert(result['message'])\r\n");
      out.write("\r\n");
      out.write("                },\r\n");
      out.write("                error: function (result, textStatus, errorThrown) {\r\n");
      out.write("                  alert(result)\r\n");
      out.write("                }\r\n");
      out.write("              })\r\n");
      out.write("            }\r\n");
      out.write("          }\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("      })\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <body class=\"is_preload\">\r\n");
      out.write("      <div class=\"page_wrapper\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.3.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("		<script>\r\n");
      out.write("			$(document).ready(function () {\r\n");
      out.write("				if(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("){\r\n");
      out.write("					if(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" == 1) $(\"#index\").attr(\"class\",'current')\r\n");
      out.write("					if(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" == 2) $(\"#product\").attr(\"class\",'current')\r\n");
      out.write("					if(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" == 3) $(\"#hospital\").attr(\"class\",'current')\r\n");
      out.write("					if(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" == 4) $(\"#community\").attr(\"class\",'current')\r\n");
      out.write("				}\r\n");
      out.write("				$('.slider-2 .page-nav > div').click(function() {\r\n");
      out.write("				    \r\n");
      out.write("				    var $this = $(this);\r\n");
      out.write("				    var $pagenav = $this.parent()\r\n");
      out.write("				    var $current = $pagenav.find('.active');\r\n");
      out.write("				    \r\n");
      out.write("				    $current.removeClass('active');\r\n");
      out.write("				    $this.addClass('active');\r\n");
      out.write("\r\n");
      out.write("				    var index = $this.index();\r\n");
      out.write("				    var $슬라이더 = $this.closest('.slider-2');\r\n");
      out.write("				    \r\n");
      out.write("				    $슬라이더.find('.slides > div.active').removeClass('active');\r\n");
      out.write("				    $슬라이더.find('.slides > div').eq(index).addClass('active');\r\n");
      out.write("				    \r\n");
      out.write("				    \r\n");
      out.write("				});\r\n");
      out.write("\r\n");
      out.write("				$('.slider-2 > .side-btns > div:first-child').click(function() {\r\n");
      out.write("				    var $this = $(this);\r\n");
      out.write("				    var $slider = $this.closest('.slider-2');\r\n");
      out.write("				    \r\n");
      out.write("				    var $current = $slider.find('.page-nav > div.active');\r\n");
      out.write("				    var $post = $current.prev();\r\n");
      out.write("				    \r\n");
      out.write("				    if ( $post.length == 0 ) {\r\n");
      out.write("				        $post = $slider.find('.page-nav > div:last-child');\r\n");
      out.write("				    }\r\n");
      out.write("				    \r\n");
      out.write("				    $post.click();\r\n");
      out.write("				});\r\n");
      out.write("\r\n");
      out.write("				$('.slider-2 > .side-btns > div:last-child').click(function() {\r\n");
      out.write("				    var $this = $(this);\r\n");
      out.write("				    var $slider = $this.closest('.slider-2');\r\n");
      out.write("				    \r\n");
      out.write("				    var $current = $slider.find('.page-nav > div.active');\r\n");
      out.write("				    var $post = $current.next();\r\n");
      out.write("				    \r\n");
      out.write("				    if ( $post.length == 0 ) {\r\n");
      out.write("				        $post = $slider.find('.page-nav > div:first-child');\r\n");
      out.write("				    }\r\n");
      out.write("				    \r\n");
      out.write("				    $post.click();\r\n");
      out.write("				});\r\n");
      out.write("				let interval = setInterval(() => {\r\n");
      out.write("					$(\".slider-2 > .side-btns > div:last-child\").click();\r\n");
      out.write("				}, 3000);\r\n");
      out.write("			})\r\n");
      out.write("		</script>\r\n");
      out.write("		<style>\r\n");
      out.write("\r\n");
      out.write(".slider-2 {\r\n");
      out.write("    height:400px;\r\n");
      out.write("    position:relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slider-2 .slides > div {\r\n");
      out.write("    position:absolute;\r\n");
      out.write("    top:0;\r\n");
      out.write("    left:0;\r\n");
      out.write("    width:100%;\r\n");
      out.write("    height:100%;\r\n");
      out.write("    background-position:center;\r\n");
      out.write("    /* 이미지를 최대한 안짤리게 한다. */\r\n");
      out.write("    background-size:cover;\r\n");
      out.write("    /* 배경 반복 금지 */\r\n");
      out.write("    background-repeat:no-repeat;\r\n");
      out.write("    opacity:0;\r\n");
      out.write("    transition: opacity 0.5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slider-2 .slides > div.active {\r\n");
      out.write("    opacity:1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( max-width:700px ) {\r\n");
      out.write("    .slider-2 {\r\n");
      out.write("        height:300px;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slider-2 .page-nav {\r\n");
      out.write("    position:absolute;\r\n");
      out.write("    width:100%;\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    bottom:0;\r\n");
      out.write("    left:0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slider-2 .page-nav > div {\r\n");
      out.write("    display:inline-block;\r\n");
      out.write("    width:15px;\r\n");
      out.write("    height:15px;\r\n");
      out.write("    background-color:rgba(255,255,255,0.5);\r\n");
      out.write("    border-radius:2px;\r\n");
      out.write("    cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slider-2 .page-nav > div.active {\r\n");
      out.write("    background-color:rgba(255,255,255,1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slider-2>.side-btns>div{\r\n");
      out.write("    position:absolute;\r\n");
      out.write("    top:0;\r\n");
      out.write("    left:0;\r\n");
      out.write("    width:30%;\r\n");
      out.write("    height:100%;\r\n");
      out.write("    cursor:pointer;\r\n");
      out.write("    z-index:10;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slider-2>.side-btns>div>span:active{\r\n");
      out.write("    transform:translatey(-40%);\r\n");
      out.write("}\r\n");
      out.write(".slider-2>.side-btns>div:last-child{\r\n");
      out.write("    left:auto;\r\n");
      out.write("    right:0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slider-2>.side-btns>div>span{\r\n");
      out.write("    position:absolute;\r\n");
      out.write("    top:50%;\r\n");
      out.write("    transform:translatey(-50%);\r\n");
      out.write("    left:inherit;\r\n");
      out.write("    right:inherit;\r\n");
      out.write("    width:70px;\r\n");
      out.write("    height:70px;\r\n");
      out.write("    background-color:rgba(255,255,255,0.4);\r\n");
      out.write("    border-radius:100%;\r\n");
      out.write("    margin:0 10px;\r\n");
      out.write("}\r\n");
      out.write(".slider-2>.side-btns>div>span > i{\r\n");
      out.write("    position:absolute;\r\n");
      out.write("    top:50%;\r\n");
      out.write("    left:50%;\r\n");
      out.write("    font-size:3rem;\r\n");
      out.write("    color:rgba(0,0,0,0.4);\r\n");
      out.write("    transform:translateX(-70%) translateY(-50%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slider-2>.side-btns>div:last-child>span > i {\r\n");
      out.write("    transform:translateX(-20%) translateY(-50%);\r\n");
      out.write("} \r\n");
      out.write("#nav ul {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  #nav ul li {\r\n");
      out.write("    margin: 0 10px;\r\n");
      out.write("  }\r\n");
      out.write("/* 슬라이드 버튼 끝 */\r\n");
      out.write("		</style>\r\n");
      out.write("		<!-- Header -->\r\n");
      out.write("		\r\n");
      out.write("		<div id=\"header\" >\r\n");
      out.write("			");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			<!-- Logo -->\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"logo\" style=\"align-items: center;\">\r\n");
      out.write("				 <div class=\"slider-2\">\r\n");
      out.write("    \r\n");
      out.write("				     <div class=\"side-btns\">\r\n");
      out.write("				        <div><span><i class=\"fas fa-caret-left\"></i></i></span></div>\r\n");
      out.write("				        <div><span><i class=\"fas fa-caret-right\"></i></span></div>\r\n");
      out.write("				    </div>\r\n");
      out.write("				    \r\n");
      out.write("				    <div class=\"slides\">\r\n");
      out.write("				       <div class=\"active\" style=\"background-image:url(https://icatcare.org/app/uploads/2019/02/CFC-website-banner-1920x660.jpg?auto=compress,format);\"></div>\r\n");
      out.write("				       <div style=\"background-image:url(https://petlifesa.com/wp-content/uploads/slider2/PLSA630-petilfesa-web-dog-banner-image-FA.jpeg?auto=compress,format);\"></div>\r\n");
      out.write("				    </div>\r\n");
      out.write("				    \r\n");
      out.write("				    <div class=\"page-nav\">\r\n");
      out.write("				        <div class=\"active\"></div>\r\n");
      out.write("				        <div></div>\r\n");
      out.write("				        \r\n");
      out.write("				    </div>\r\n");
      out.write("				</div>\r\n");
      out.write("				  \r\n");
      out.write("				  \r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Nav -->\r\n");
      out.write("			<nav id=\"nav\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li id='index' ><a href=\"/ipet/index\">메인 페이지</a></li>\r\n");
      out.write("					<li id='product'><a href=\"/ipet/pro\">반려동물 용품 판매</a>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"/products/food\">사료/간식</a></li>\r\n");
      out.write("							<li><a href=\"/products/pad\">패드/장난감</a></li>\r\n");
      out.write("							<li><a href=\"/products/bath\">목욕/하네스</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li id='hospital'><a href=\"/ipet/hos\">동물병원 검색</a></li>\r\n");
      out.write("					<li id='community'><a href=\"/ipet/community\">커뮤니티</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<!-- Scripts -->\r\n");
      out.write("				<script src=\"../resources/assets/js/jquery.min.js\"></script>\r\n");
      out.write("				<script src=\"../resources/assets/js/jquery.dropotron.min.js\"></script>\r\n");
      out.write("				<script src=\"../resources/assets/js/browser.min.js\"></script>\r\n");
      out.write("				<script src=\"../resources/assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("				<script src=\"../resources/assets/js/util.js\"></script>\r\n");
      out.write("				<script src=\"../resources/assets/js/main.js\"></script>\r\n");
      out.write("			</nav>\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("          <section class=\"wrapper style1\">\r\n");
      out.write("            <section class=\"container\">\r\n");
      out.write("              <div id=\"content\">\r\n");
      out.write("                <div class=\"login-wrapper\"\r\n");
      out.write("                  style=\"display: flex; justify-content: center; align-items: center; margin-bottom: 20px;\">\r\n");
      out.write("                  <form action=\"#\" method=\"post\">\r\n");
      out.write("                    아이디&nbsp; <input type='text' id=\"mid\" name=\"id\"\r\n");
      out.write("                      style=\"width:380px; height:42px;text-align: center;\" /><br />\r\n");
      out.write("                    비밀번호 <input id=\"mpassword\" type=\"password\" name='password'\r\n");
      out.write("                      style=\"width:380px; height:42px;text-align: center;\" /><br />\r\n");
      out.write("                    <button id=\"login\" type=\"button\"> 로그인 </button> &nbsp;\r\n");
      out.write("                    <button id=\"findId\" type=\"button\" data-toggle=\"modal\" data-target=\"#findModal\"> 아이디 찾기\r\n");
      out.write("                    </button>&nbsp;\r\n");
      out.write("                    <button id=\"findPassword\" type=\"button\" data-toggle=\"modal\" data-target=\"#findModal\"> 비밀번호 찾기\r\n");
      out.write("                    </button>&nbsp;\r\n");
      out.write("                  </form>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"ad-wrapper\"\r\n");
      out.write("                  style=\"display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px;\">\r\n");
      out.write("                  <a href=\"https://www.lacoste.com/kr/90-anniversary.html?utm_source=naver&utm_medium=branding&utm_campaign=kr_brandcampaign-ss23reach_&utm_term=coupleboard&utm_content=vintage;\"\r\n");
      out.write("                    id=\"ac_banner_a\" target=\"_blank\">\r\n");
      out.write("                    <img\r\n");
      out.write("                      src=\"	https://ssl.pstatic.net/melona/libs/1442/1442950/d1a9361bd50c99be2d31_20230428111327912.jpg\"\r\n");
      out.write("                      alt=\"광고 이미지\" style=\"width: 1400px; height: 200px;\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </section>\r\n");
      out.write("          </section>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal fade\" id=\"findModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"findModalLabel\"\r\n");
      out.write("        aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("          <div class=\"modal-content\">\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("		<div id=\"footer\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<section class=\"col-3 col-6-narrower col-12-mobilep\">\r\n");
      out.write("						<h3>연락처</h3>\r\n");
      out.write("						<ul class=\"links\">\r\n");
      out.write("							<li>팀장: 양강철</li>\r\n");
      out.write("							<li>팀원: 신민경</li>						\r\n");
      out.write("							<!--  \r\n");
      out.write("							<li><a href=\"#\">Mattis et quis rutrum</a></li>\r\n");
      out.write("							<li><a href=\"#\">Suspendisse amet varius</a></li>\r\n");
      out.write("							<li><a href=\"#\">Sed et dapibus quis</a></li>\r\n");
      out.write("							<li><a href=\"#\">Rutrum accumsan dolor</a></li>\r\n");
      out.write("							<li><a href=\"#\">Mattis rutrum accumsan</a></li>\r\n");
      out.write("							<li><a href=\"#\">Suspendisse varius nibh</a></li>\r\n");
      out.write("							<li><a href=\"#\">Sed et dapibus mattis</a></li>\r\n");
      out.write("						 -->\r\n");
      out.write("						 </ul>\r\n");
      out.write("					</section>\r\n");
      out.write("					<!--\r\n");
      out.write("					<section class=\"col-3 col-6-narrower col-12-mobilep\">\r\n");
      out.write("						<h3>More Links to Stuff</h3>\r\n");
      out.write("						<ul class=\"links\">\r\n");
      out.write("							<li><a href=\"#\">Duis neque nisi dapibus</a></li>\r\n");
      out.write("							<li><a href=\"#\">Sed et dapibus quis</a></li>\r\n");
      out.write("							<li><a href=\"#\">Rutrum accumsan sed</a></li>\r\n");
      out.write("							<li><a href=\"#\">Mattis et sed accumsan</a></li>\r\n");
      out.write("							<li><a href=\"#\">Duis neque nisi sed</a></li>\r\n");
      out.write("							<li><a href=\"#\">Sed et dapibus quis</a></li>\r\n");
      out.write("							<li><a href=\"#\">Rutrum amet varius</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</section> -->\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("			<!-- Copyright -->\r\n");
      out.write("			<div class=\"copyright\">\r\n");
      out.write("				<ul class=\"menu\">\r\n");
      out.write("					<li>&copy; 이젠아카데미 KM 팀</li>\r\n");
      out.write("					\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Scripts -->\r\n");
      out.write("			<script src=\"../resources/assets/js/jquery.min.js\"></script>\r\n");
      out.write("			<script src=\"../resources/assets/js/jquery.dropotron.min.js\"></script>\r\n");
      out.write("			<script src=\"../resources/assets/js/browser.min.js\"></script>\r\n");
      out.write("			<script src=\"../resources/assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("			<script src=\"../resources/assets/js/util.js\"></script>\r\n");
      out.write("			<script src=\"../resources/assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("		</div>");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("				");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("				");
          if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/member/../header.jsp(175,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty loginMember.mno}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<span style=\"text-align: right; display: block\">\r\n");
          out.write("						<a style=\"color: black;\" href=\"/ipet/index\">홈으로</a> &nbsp; &nbsp;\r\n");
          out.write("						<a style=\"color: black;\" href=\"/member/login\">로그인</a> &nbsp; &nbsp;\r\n");
          out.write("						<a style=\"color: black;\" href=\"/member/register\">회원가입</a>\r\n");
          out.write("					</span>\r\n");
          out.write("					<br />\r\n");
          out.write("					<span id=\"timer\"></span>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/member/../header.jsp(184,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty loginMember.mno && loginMember.auth eq 'm'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<span style=\"text-align: right; display: block\">\r\n");
          out.write("					<a style=\"color: black;\" href=\"/ipet/index\">홈으로</a> &nbsp; &nbsp;\r\n");
          out.write("						<a style=\"color: black;\" href=\"/member/mypage\">마이페이지</a> &nbsp; &nbsp;\r\n");
          out.write("						<a style=\"color: black;\" href=\"/member/cart\">장바구니</a> &nbsp; &nbsp;\r\n");
          out.write("						<a style=\"color: black;\" href=\"/member/logout\">로그아웃</a>\r\n");
          out.write("						<br />\r\n");
          out.write("						<span style=\"text-align: right; display: block;\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님</span>\r\n");
          out.write("					</span>\r\n");
          out.write("\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f2_reused = false;
    try {
      _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/member/../header.jsp(195,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty loginMember.mno && loginMember.auth eq 'a'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
      if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<span style=\"text-align: right; display: block\">\r\n");
          out.write("						<a style=\"color: black;\" href=\"/ipet/index\">홈으로</a> &nbsp; &nbsp;\r\n");
          out.write("						<a style=\"color: black;\" href=\"/admin/member\">관리자 페이지</a> &nbsp; &nbsp;\r\n");
          out.write("						<a style=\"color: black;\" href=\"/member/mypage\">마이페이지</a> &nbsp; &nbsp;\r\n");
          out.write("						<a style=\"color: black;\" href=\"/member/logout\">로그아웃</a>\r\n");
          out.write("						<br />\r\n");
          out.write("						<span style=\"text-align: right; display: block;\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님</span>\r\n");
          out.write("					</span>\r\n");
          out.write("\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      _jspx_th_c_005fwhen_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f2_reused);
    }
    return false;
  }
}
